### ISSUE TITLE
How to use native tls with tokio_tls feature?

### ISSUE THREAD

**Issue by xyaman** [sdroege/async-tungstenite#31]

**Comment by sdroege** [comment]
What's exactly the problem here? When enabling the `tokio-tls` feature, TLS connections would be done via `tokio-tls`, which uses `native-tls` (i.e. SChannel on Windows, Secure Transport on macOS/iOS, OpenSSL elsewhere).

This should be moved from `tokio-tls` to `tokio-native-tls` on the next breaking release, but that should be basically the same.

**Comment by xyaman** [comment]
Sorry, I was thinking that tokio-tls uses openssl, because my program needed openssl, then I realized that was another crate. My bad

**Comment by sdroege** [comment]
Ok, no worries :)
