### ISSUE TITLE
Examples for WSS server with Tungstenite

### ISSUE THREAD

**Issue by Redrield** [sdroege/async-tungstenite#49]
I'm unclear the method to accept clients wishing to communicate over TLS. From looking at the code I don't see a definition of any `accept` function under the TLS modules, and there aren't examples for this usecase either.

**Comment by sdroege** [comment]
It works exactly like the [`server`](https://github.com/sdroege/async-tungstenite/blob/master/examples/server.rs) example, just that instead of accepting connections on a `TcpConnection` directly you would e.g. use the [`TlsAcceptor`](https://docs.rs/async-native-tls/0.3.3/async_native_tls/struct.TlsAcceptor.html) from `async-native-tls` in between to get the stream that is passed to `async_tungstenite::accept_async`.
